### ISSUE TITLE
Help!  opengles3 book sample code build failed, error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by JieX** [danginsburg/opengles3-book#21]
I have tried to build the sample code on Visual Studio 2008 with the guide in Chapter 16. I used PowerVR  SDK 3.5 on windows 7. I have set EGL_LIBRARY & OPENGLE3_LIBRARY to right path: D:\Imagination\PowerVR_Graphics\PowerVR_SDK\SDK_3.5\Builds\Windows\x86_64\Lib\libEGL.lib & libGLESv2.lib. But when i built the Hello_Triangle sample code, i got the following errors. I have tried some ways to fix it but failed. Does  anyone have the same problem? Please help me.

2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glDeleteShader@4 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glGetShaderInfoLog@16 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glGetShaderiv@12 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glCompileShader@4 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glShaderSource@16 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glCreateShader@4 referenced in function _LoadShader
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glClearColor@16 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glDeleteProgram@4 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glGetProgramInfoLog@16 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glGetProgramiv@12 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glLinkProgram@4 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glAttachShader@8 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glCreateProgram@0 referenced in function _Init
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glDrawArrays@12 referenced in function _Draw
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glEnableVertexAttribArray@4 referenced in function _Draw
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glVertexAttribPointer@24 referenced in function _Draw
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glUseProgram@4 referenced in function _Draw
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glClear@4 referenced in function _Draw
2>Hello_Triangle.obj : error LNK2019: unresolved external symbol __imp__glViewport@16 referenced in function _Draw
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglQueryString@8 referenced in function _GetContextRenderableType
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglMakeCurrent@16 referenced in function _esCreateWindow
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglCreateContext@16 referenced in function _esCreateWindow
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglCreateWindowSurface@16 referenced in function _esCreateWindow
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglChooseConfig@20 referenced in function _esCreateWindow
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglInitialize@12 referenced in function _esCreateWindow
2>Common.lib(esUtil.obj) : error LNK2019: unresolved external symbol __imp__eglGetDisplay@4 referenced in function _esCreateWindow
2>Common.lib(esUtil_win32.obj) : error LNK2019: unresolved external symbol __imp__eglSwapBuffers@8 referenced in function _ESWindowProc@16

**Comment by danginsburg** [comment]
Is it possible you are doing a 32-bit build and not a 64-bit build?  If that's the case, you would need to link against D:\Imagination\PowerVR_Graphics\PowerVR_SDK\SDK_3.5\Builds\Windows\x86_32\Lib\libEGL.lib & libGLESv2.lib.  Either that, or make sure you pick the 32-bit generator in cmake rather than Win64.

I can't think of anything else offhand that would cause this.  It works fine with VS 2013.  I don't have VS 2008 installed at the moment, but I would have expected it to work.

**Comment by JieX** [comment]
Hi, Dan.
     Thank you for your advice. I have fix the link error on my 64bit windows 7 after i chose VS 64bit in cmake and set library to 64 bit path. But i got another error message "Unhandled exception at 0x00000000 in Hello_Triangle.exe: 0xC0000005: Access violation reading location 0x0000000000000000." The error message occured when call eglInitialize() in esCreateWindow(), does it mean the gl lib&dll have configured correctly as eglGetDisplay() didn't get a error beforce calling eglInitialize().

**Comment by JieX** [comment]
I think this is a PowerVR_SDK configuration issue, the 32bit project works well after i set Edit -> Preferences -> Context creation mode = Loose in  PVRVFrameGUI.

**Comment by vikydattu** [comment]
I am getting this runtime error on visual studio 2010.
Please help.

![capture4](https://cloud.githubusercontent.com/assets/5511751/10067208/1877e34e-62b8-11e5-9dfe-1a72dbdb6241.PNG)

**Comment by JieX** [comment]
You can try to put the missing dll into the same direction of the *.exe.
